# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "Mapclub Block"
handle = "mapclub-block"
type = "ui_extension"
uid = "8c90d617-094d-8754-6dd2-9b5c1a17d84cc19e290d"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

# Request access to customer metafields
[[extensions.metafields]]
namespace = "custom"
key = "mapclub_member_code"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
# network_access = true

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#settings-definition

[extensions.settings]
  [[extensions.settings.fields]]
  key = "shop_domain"
  type = "single_line_text_field"
  name = "Shop Domain"
  
  [[extensions.settings.fields]]
  key = "storefront_token"
  type = "single_line_text_field"
  name = "Storefront Access Token"