# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07db3587d48ecb6f1b1d43fa1e2ccfe2"
name = "MAPCLUB MaaS MAA"
application_url = "https://many-decent-garfish.ngrok-free.app/"
embedded = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_customers,write_products"

[auth]
redirect_urls = [
  "https://many-decent-garfish.ngrok-free.app/auth/callback",
  "https://many-decent-garfish.ngrok-free.app/auth/shopify/callback",
  "https://many-decent-garfish.ngrok-free.app/api/auth/callback"
]

[app_proxy]
url = "https://many-decent-garfish.ngrok-free.app"
subpath = "mapclub"
prefix = "apps"

[build]
automatically_update_urls_on_dev = true
